### PR TITLE
updates categories with icons and new attributes

### PR DESCRIPTION
**Pull request by randymeech**
### This PR
1. Updates icons with current bubble wrap icons
2. Adds category-dependent attributes
3. Removes some duplicates & unneeded categories

#### New icons
Now the icons are available in our own S3 bucket in three sizes:
- https://s3.amazonaws.com/mapicons.streetcred.co/1x/theatre.png (12x12)
- https://s3.amazonaws.com/mapicons.streetcred.co/2x/theatre.png (24x24)
- https://s3.amazonaws.com/mapicons.streetcred.co/3x/theatre.png (36x36)

#### Category-dependent attributes
Categories now have attributes as follows:
```
{
  "id": 2020,
  "name": "Post Office",
  "icon": "post",
  "attributes": [{
    "name": "Hours",
    "type": "object",
    "required": true
  }, {
    "name": "Phone",
    "type": "string",
    "required": false
  }]
}
```

### CODE REVIEW

**Comment by tylergaw** [comment]
@randymeech For attributes of type `object`. Is there any suggested shape for that object? Or can it be any valid JSON?

**Comment by randymeech** [comment]
@tylergaw In this case it would be a JSON object representing hours which @dianashk will define. Let me know if this should change here, for example to `hours_object`

**Comment by tylergaw** [comment]
@randymeech I think "object" works. Was just thinking about this project farther out. If we're suggesting other people use this data and what having things like types and `required` means for that. Could be as simple as us writing about how we use this data in our project(s) and providing those as examples. Nothing needed for now though.

**Comment by tylergaw** [comment]
I'm looking a bit closer at the data and a little confused on expectations in a couple places. I notice in some cases, "parent" categories have attributes on them like https://github.com/streetcredlabs/categories/blob/6bdf2fbd34cfd251388628e8adb984a99e4f3f05/src/data/categories.json#L318 but in that case, none of the "child" categories have attributes. we currently don't allow users to choose those "parent" categories, only "child" or "terminal" categories. Is the idea that all children inherit parent attributes? If so, what does that mean for child categories that do have attributes? like https://github.com/streetcredlabs/categories/blob/6bdf2fbd34cfd251388628e8adb984a99e4f3f05/src/data/categories.json#L187

Is there an expectation for which attributes win out if there is a conflict? Or is it a merge situation?

**Comment by randymeech** [comment]
@tylergaw the idea is that children should inherit the parent's attributes. children can also have their own attributes too.

For example `Dining` has attributes that should apply to all the children: https://github.com/streetcredlabs/categories/blob/6bdf2fbd34cfd251388628e8adb984a99e4f3f05/src/data/categories.json#L784

If it's easier, I can add all the attributes on the children as well.

**Comment by tylergaw** [comment]
OK, yeah since this data is supposed to be a standalone thing, I think it would be more clear (and easier to implement) for the attributes to live on each category as expected.

Another idea I was just wondering about. Not sure if this is a good or bad idea or not something we want to do.

**Pull request merged**
